affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kops.k8s.io/instancegroup
          operator: In
          values:
          - workloads
