apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: sandbox-tools.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://sandbox-tools-mnet-dev-state-store/sandbox-tools.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ca-central-1a-1
      name: "1"
    - instanceGroup: master-ca-central-1a-2
      name: "2"
    - instanceGroup: master-ca-central-1a-3
      name: "3"
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ca-central-1a-1
      name: "1"
    - instanceGroup: master-ca-central-1a-2
      name: "2"
    - instanceGroup: master-ca-central-1a-3
      name: "3"
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.10
  masterPublicName: api.sandbox-tools.k8s.local
  networkCIDR: 172.31.0.0/16
  networkID: vpc-665f310e
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.32.0/19
    name: ca-central-1a
    type: Private
    zone: ca-central-1a
  - cidr: 172.31.64.0/19
    name: ca-central-1b
    type: Private
    zone: ca-central-1b
  - cidr: 172.31.128.0/22
    name: utility-ca-central-1a
    type: Utility
    zone: ca-central-1a
  - cidr: 172.31.160.0/22
    name: utility-ca-central-1b
    type: Utility
    zone: ca-central-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: sandbox-tools.k8s.local
  name: master-ca-central-1a-1
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1a-1
  role: Master
  rootVolumeSize: 64
  subnets:
  - ca-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: sandbox-tools.k8s.local
  name: master-ca-central-1a-2
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1a-2
  role: Master
  rootVolumeSize: 64
  subnets:
  - ca-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: sandbox-tools.k8s.local
  name: master-ca-central-1a-3
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1a-3
  role: Master
  rootVolumeSize: 64
  subnets:
  - ca-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: sandbox-tools.k8s.local
  name: workloads
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: m5a.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: workloads
  role: Node
  rootVolumeSize: 64
  subnets:
  - ca-central-1a
  - ca-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: sandbox-tools.k8s.local
  name: stores
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: m5a.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: stores
  role: Node
  rootVolumeSize: 64
  subnets:
  - ca-central-1a
  - ca-central-1b

